name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.2.0
      - uses: actions/setup-node@v3
        with:
          node-version: 24.3.0
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build Plugin
        run: pnpm blog:plugin

      - name: Build
        run: pnpm blog:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/blog/.vitepress/dist
